"""Functions to interoperate with other parsed corpus software."""


def strip_corpussearch_comments(s):
    """Remove CorpusSearch style comments from a string.

    This function removes two types of comments from a string.  The first is
    generated by CorpusSearch, and takes the form of blocks delimited by
    ``/*`` ... ``*/`` and ``/~*`` ... ``*~/``.  The second are single line
    comments of the form ``<+ ... +>`` generated by emacs parser-mode (or some
    other awful relic).

    Args:
        s (str): the string to operate on.
    Returns:
        str: ``s`` with comments stripped.

    """
    output = []
    comment = False
    for line in s.split("\n"):
        if line.startswith("/*") or line.startswith("/~*"):
            comment = True
        elif line.startswith("<+"):
            # Ignore parser-mode comments
            pass
        elif not comment:
            output.append(line)
        elif line.startswith("*/") or line.startswith("*~/"):
            comment = False
        else:  # pragma: no cover
            # Should never happen!
            raise Exception("Something has gone very wrong while removing comments")

    if comment:
        raise Exception("Unterminated comment in input file!")

    return "\n".join(output)
