language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"
script: nosetests

after_success:
  - "make docs"

secure: "DUm8EDu6YRlfXk/BoGy7fsTtuMKWyjaMwkjKAKuDq/+vBAouTY163j8xtSqbwEnyW7x1EfUM7S4dbz+e77S6X1pxbf1i+29swk+LvTTNoLo11YqMtm+vZqQD+sCaf5ipq5TMv8Fjcpp1omGAXd3R3W4gMvNztRxGxmjV1wFe1hI="

env:
  GH_REF: github.com/aecay/lovett.git
